sampled_epids_1 <- data.table(read_csv(here::here('data','epi','sampled_epids',paste0('sampled_epidemics_30_100_ARG','_wr0.csv')), show_col_types=F))
sampled_epids_2 <- data.table(read_csv(here::here('data','epi','sampled_epids',paste0('sampled_epidemics_30_100_AUS','_wr0.csv')), show_col_types=F))
sampled_epids_3 <- data.table(read_csv(here::here('data','epi','sampled_epids',paste0('sampled_epidemics_30_100_CAN','_wr0.csv')), show_col_types=F))
sampled_epids_4 <- data.table(read_csv(here::here('data','epi','sampled_epids',paste0('sampled_epidemics_30_100_CHN','_wr0.csv')), show_col_types=F))
sampled_epids_5 <- data.table(read_csv(here::here('data','epi','sampled_epids',paste0('sampled_epidemics_30_100_GBR','_wr0.csv')), show_col_types=F))
sampled_epids_6 <- data.table(read_csv(here::here('data','epi','sampled_epids',paste0('sampled_epidemics_30_100_GHA','_wr0.csv')), show_col_types=F))
sampled_epids_7 <- data.table(read_csv(here::here('data','epi','sampled_epids',paste0('sampled_epidemics_30_100_TUR','_wr0.csv')), show_col_types=F))

combined_transmissibility <- c(sampled_epids_1$trans, sampled_epids_2$trans, sampled_epids_3$trans, sampled_epids_4$trans, sampled_epids_5$trans, sampled_epids_6$trans, sampled_epids_7$trans)
quantile(combined_transmissibility)
