#### load relevant packages ####

install.packages(readr)
install.packages(dplyr)
install.packages(data.table)
install.packages(odin)
install.packages(parallel)
install.packages(cleaner)
install.packages(countrycode)
install.packages(ggplot2)
install.packages(readxl)
install.packages(tidyverse)
install.packages(viridis)
install.packages(patchwork)
install.packages(wpp2022)
install.packages(fluEvidenceSynthesis)
install.packages(parallel)
install.packages(openxlsx)
install.packages(stringr)
install.packages(purrr)
install.packages(DescTools)

library(readr)
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(data.table))
library(odin)
library(parallel)
library(cleaner)
library(countrycode)
library(ggplot2)
library(readxl)
suppressPackageStartupMessages(library(tidyverse))
library(viridis)
library(patchwork)
library(wpp2022)
library(WDI)
suppressPackageStartupMessages(library(fluEvidenceSynthesis))
library(parallel)
library(openxlsx)
library(stringr)
library(purrr)
library(DescTools)

select <- dplyr::select



